# Generated by Django 3.2 on 2023-05-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
