# Generated by Django 3.2 on 2023-08-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_contactmessage_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio_item',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
